// LOCALHOST
###
GET http://localhost:8080/contacts
###
GET http://localhost:8080/contacts/62a804897f6ca83cc742a7c8
###
GET http://localhost:8080/contacts/62a804897f6ca83cc742a7c9
###
GET http://localhost:8080/contacts/62a804897f6ca83cc742a7ca

// PRODUCTION Deploy
###
GET https://cse341node-dc.herokuapp.com/contacts
###
GET https://cse341node-dc.herokuapp.com/contacts/62a804897f6ca83cc742a7c8
###
GET https://cse341node-dc.herokuapp.com/contacts/62a804897f6ca83cc742a7c9
###
GET https://cse341node-dc.herokuapp.com/contacts/62a804897f6ca83cc742a7ca
